config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'welcome/index'

  resources :group, param: :code, only: [:show, :create, :update, :destroy] do
    resources :people, only: [:create, :update, :destroy]
    resources :rules, only: [:create, :update, :destroy] do
      resources :tokens, only: [:create, :update, :destroy]
    end
  end

  resources :users

  root 'welcome#index'

  get     '/group/:code/admin',     to: 'group#show'
  get     '/signup',                to: 'users#new'
  get     '/login',                 to: 'sessions#new'
  post    '/',                      to: 'group#create'
  post    '/search',                to: 'group#search'
  post    '/group/:code/generate',  to: 'group#randomize',  as: 'generate'
  post    '/group/:code/duplicate',  to: 'group#duplicate',  as: 'duplicate'
  post    '/group/:code/clear',     to: 'group#clear',      as: 'clear'
  post    '/signup',                to: 'users#create'
  post    '/login',                 to: 'sessions#create'
  delete  '/logout',                to: 'sessions#destroy'
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :group
  validates :name, presence: true, length: { maximum: 50 }
  validates :family, length: { maximum: 50 }

  def apply_rules(people, rules)
  	rules.each { |rule|
  		if people.reject { |person| rule.check_source(self) && !rule.check_rule(person) }.length >= 1
  			people.reject! { |person| rule.check_source(self) && !rule.check_rule(person) }
  		end
  	}
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def create
    @group = Group.find_by(code: params[:group_code])

    if current_user && current_user.id == @group.user_id
      @person = @group.people.create(person_params)
    elsif @group.open? && current_user && @group.people.none?{|person| person.user_id==current_user.id}
      @person = @group.people.create(person_params_restricted)
    end
  end

  def update
    @group = Group.find_by(code: params[:group_code])

    if current_user && (current_user.id == @group.user_id || @group.people.any?{|person|person.user_id==current_user.id})
      @person = @group.people.find(params[:id])

      @person.update(person_params) if @person
    end
  end

  def destroy
    @group = Group.find_by(code: params[:group_code])

    if current_user && (current_user.id == @group.user_id || @group.people.any?{|person|person.user_id==current_user.id})
      @person = @group.people.find(params[:id])

      @person.destroy if @person
    end
  end

  private

    def person_params
      params.require(:person).permit(:name, :family, :participating, :user_id)
    end

    def person_params_restricted
      params.require(:person).permit(:name, :user_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<% if logged_in? %>
  <% if not @group.people.any?{|person| person.user_id == current_user.id} %>
    <span class="card-title">Join Group</span><br>
    <% if @group.open? %>
      <%= form_for [@group, @group.people.build], remote: true do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="input-field">
          <%= f.label :name %>
          <%= f.text_field :name, value: current_user.name %>
        </div>
        <%= f.submit "Join Group", class: "btn-flat waves-effect waves-light" %>
      <% end %>
    <% else %>
      <h5>Submissions Closed</h5>
    <% end %>
  <% else %>
    <% person=@group.people.select{|person|person.user_id==current_user.id}.first %>
    <span class="card-title"><%= person.name %></span><br>
    <%= form_for [@group, person], remote: true do |f| %>
      <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %>
        Sending to: 
        <p style="display: inline;">
          <% giving =  Person.find(person.giving_to) %>
          <% if giving.user_id and User.exists?(giving.user_id) %>
            <%= link_to giving.name, User.find(giving.user_id) %>
          <% else %>
            <%= giving.name %>
          <% end %>
        </p><br>
      <% end %>
      <% if not person.receiving_from.nil? and Person.exists?(person.receiving_from) and @group.public? %>
        Receiving from: 
        <p style="display: inline;">
          <% receiving =  Person.find(person.receiving_from) %>
          <% if receiving.user_id and User.exists?(receiving.user_id) %>
            <%= link_to receiving.name, User.find(receiving.user_id) %>
          <% else %>
            <%= receiving.name %>
          <% end %>
        </p><br>
      <% end %>
      <br>
      <div class="input-field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <%= f.submit class: "btn-flat waves-effect waves-light" %>
      <%= link_to "Leave Group", group_person_path(@group, person), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "btn-flat waves-effect waves-light delete_person", style: "float: right;" %>
    <% end %>
  <% end %>
<% else %>
  <span class="card-title">Join Group</span><br>
  <p>Before you can join, you need to either <%= link_to "register", signup_path %> or <%= link_to "login", login_path %></p>
<% end %>

app/views/people/_person.html.erb
<% if not person.id.nil? %>
  <% if current_user && current_user.id == @group.user_id %>
    <li class="person" id="person_<%= person.id %>">
      <div class="collapsible-header">
        <% if person.user_id && User.exists?(person.user_id) && User.find(person.user_id).public_avatar %>
          <%= gravatar_for(User.find(person.user_id)) %>
        <% else %>
          <i class="material-icons">face</i>
        <% end %>
        <%= person.name %>
        <p id="person_<%= person.id %>_sending_header" style="display: inline;color: grey;">
          <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %> ⇒ <%= Person.find(person.giving_to).name %>
          <% end %>
        </p>
      </div>
      <div class="collapsible-body">
        <%= form_for [@group, person], remote: true do |f| %>
          Sending to: 
          <p id="person_<%= person.id %>_sending" style="display: inline;">
            <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %>
              <% giving =  Person.find(person.giving_to) %>
              <% if giving.user_id and User.exists?(giving.user_id) %>
                <%= link_to giving.name, User.find(giving.user_id) %>
              <% else %>
                <%= giving.name %>
              <% end %>
            <% end %>
          </p><br>
          Receiving from: 
          <p id="person_<%= person.id %>_receiving" style="display: inline;">
            <% if not person.receiving_from.nil? and Person.exists?(person.receiving_from) %>
              <% receiving =  Person.find(person.receiving_from) %>
              <% if receiving.user_id and User.exists?(receiving.user_id) %>
                <%= link_to receiving.name, User.find(receiving.user_id) %>
              <% else %>
                <%= receiving.name %>
              <% end %>
            <% end %>
          </p><br><br>
          <div class="input-field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <div class="input-field">
            <%= f.label :family, "Class" %>
            <%= f.text_field :family %>
          </div>
          <%= f.label :participating %>
          <div class="switch" style="margin-bottom: 2rem;margin-top: 1rem;">
            <label>Off <%= f.check_box :participating %><span class="lever"></span> On</label>
          </div>
          <%= f.submit class: "btn-flat waves-effect waves-light" %>
          <%= link_to "Delete", group_person_path(@group, person), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "btn-flat waves-effect waves-light delete_person", style: "float: right;" %>
        <% end %>
      </div>
    </li>
  <% elsif @group.public? %>
    <li class="person" id="person_<%= person.id %>">
      <div class="collapsible-header">
        <% if person.user_id && User.exists?(person.user_id) && User.find(person.user_id).public_avatar %>
          <%= gravatar_for(User.find(person.user_id)) %>
        <% else %>
          <i class="material-icons">face</i>
        <% end %>
        <%= person.name %>
        <p id="person_<%= person.id %>_sending_header" style="display: inline;color: grey;">
        <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %> ⇒ <%= Person.find(person.giving_to).name %>
        <% end %></p>
      </div>
      <div class="collapsible-body">
        Sending to: 
        <p id="person_<%= person.id %>_sending" style="display: inline;">
          <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %>
            <% giving =  Person.find(person.giving_to) %>
            <% if giving.user_id and User.exists?(giving.user_id) %>
              <%= link_to giving.name, User.find(giving.user_id) %>
            <% else %>
              <%= giving.name %>
            <% end %>
          <% end %>
        </p><br>
        Receiving from: 
        <p id="person_<%= person.id %>_receiving" style="display: inline;">
          <% if not person.receiving_from.nil? and Person.exists?(person.receiving_from) %>
            <% receiving =  Person.find(person.receiving_from) %>
            <% if receiving.user_id and User.exists?(receiving.user_id) %>
              <%= link_to receiving.name, User.find(receiving.user_id) %>
            <% else %>
              <%= receiving.name %>
            <% end %>
          <% end %>
        </p>
      </div>
    </li>
  <% else %>
    <li id="person_<%= person.id %>_sending_header" class="collection-item" id="person_<%= person.id %>">
      <% if person.user_id && User.exists?(person.user_id) && User.find(person.user_id).public_avatar %>
        <%= gravatar_for(User.find(person.user_id)) %>
      <% else %>
        <i class="material-icons">face</i>
      <% end %>
      <%= person.name %>
    </li>
  <% end %>
<% end %>

app/views/people/create.js.erb
<% if @person.errors.any? %>
  $("#error_explanation").html('<ul class="collection with-header"><li class="collection-header"><h4><%= j pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h4></li><% @person.errors.full_messages.each do |msg| %><li class="collection-item"><%= j msg %></li><% end %></ul>');
<% else %>
  $("#error_explanation").html('');
  $("#people").append("<%= j (render @person) %>");
  $("#join_group").html("<%= j (render 'people/form') %>");
  $("#join_group_admin").html('');
  Materialize.updateTextFields();
<% end %>

app/views/people/destroy.js.erb
$("#person_<%= @person.id %>").remove();
<% if @person.user_id && @person.user_id == @group.user.id %>
	$("#join_group_admin").html('<div class="collapsible-header"><i class="material-icons">mode_edit</i>Join Group</div><div class="collapsible-body"><%= form_for [@group, Person.new], remote: true do |f| %><%= f.hidden_field :user_id, value: current_user.id %><div class="input-field"><%= f.label :name %><%= f.text_field :name, value: current_user.name %></div><div class="input-field"><%= f.label :family, "Class" %><%= f.text_field :family %></div><%= f.label :participating %><div class="switch" style="margin-bottom: 2rem;margin-top: 1rem;"><label>Off <%= f.check_box :participating %><span class="lever"></span> On</label></div><%= f.submit "Join Group", class: "btn-flat waves-effect waves-light" %><% end %></div>');
<% else %>
	$("#join_group").html('<span class="card-title">Join Group</span><br><% if @group.open? %><%= form_for [@group, @group.people.build], remote: true do |f| %><%= f.hidden_field :user_id, value: current_user.id %><div class="input-field"><%= f.label :name %><%= f.text_field :name, value: current_user.name %></div><%= f.submit "Join Group", class: "btn-flat waves-effect waves-light" %><% end %><% else %><h5>Submissions Closed</h5><% end %>');
<% end %>
Materialize.updateTextFields();

app/views/people/update.js.erb
<% if @person.errors.any? %>
  $("#error_explanation_person").html('<ul class="collection with-header"><li class="collection-header"><h4><%= j pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h4></li><% @person.errors.full_messages.each do |msg| %><li class="collection-item"><%= j msg %></li><% end %></ul>');
<% else %>
  $("#error_explanation_person").html('');
  $("#person_<%= @person.id %>").replaceWith('<%= j render @person %>')
<% end %>