config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'welcome/index'

  resources :group, param: :code, only: [:show, :create, :update, :destroy] do
    resources :people, only: [:create, :update, :destroy]
    resources :rules, only: [:create, :update, :destroy] do
      resources :tokens, only: [:create, :update, :destroy]
    end
  end

  resources :users

  root 'welcome#index'

  get     '/group/:code/admin',     to: 'group#show'
  get     '/signup',                to: 'users#new'
  get     '/login',                 to: 'sessions#new'
  post    '/',                      to: 'group#create'
  post    '/search',                to: 'group#search'
  post    '/group/:code/generate',  to: 'group#randomize',  as: 'generate'
  post    '/group/:code/duplicate',  to: 'group#duplicate',  as: 'duplicate'
  post    '/group/:code/clear',     to: 'group#clear',      as: 'clear'
  post    '/signup',                to: 'users#create'
  post    '/login',                 to: 'sessions#create'
  delete  '/logout',                to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :groups
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
  	format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
  	uniqueness: { case_sensitive: false }
  validates :interests, length: { maximum: 1000 }

  has_secure_password
  validates :password, presence: true, length: {minimum: 5, maximum: 120}, on: :create
  validates :password, length: {minimum: 5, maximum: 120}, on: :update, allow_blank: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :store_target_location, :except => :show

  def show
  	@user = User.find(params[:id])
    if current_user == @user
      @group = Group.new
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "Welcome to Name Draw! You are now logged in."
      redirect_to_target_or_default(@user)
    else
  		render 'new'
  	end
  end

  def update
    @user = User.find(params[:id])

    if @user && current_user && current_user == @user
      @user.update_attributes(user_params)
    end
  end

  private

	  def user_params
	    params.require(:user).permit(:name, :email, :password, :password_confirmation, :interests, :public_avatar)
	  end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "circle responsive-img")
	end
end

app/views/users/new.html.erb
<% @title="Sign Up" %>

<% if @user.errors.any? %>
	<div id="error_explanation" class="card" style="color: red;">
		<ul class="collection with-header">
			<li class="collection-header">
				<h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>
			</li>
			<% @user.errors.full_messages.each do |msg| %>
				<li class="collection-item"><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="card">
	<div class="card-content">
		<%= form_for(@user, url: signup_path) do |f| %>
			<div class="input-field">
          		<%= f.label :name %>
          		<%= f.text_field :name %>
        	</div>

        	<div class="input-field">
	     		<%= f.label :email %>
	     		<%= f.email_field :email %>
	     	</div>

	     	<div class="input-field">
	     		<%= f.label :password %>
	     		<%= f.password_field :password %>
	     	</div>

	     	<div class="input-field">
	     		<%= f.label :password_confirmation, "Confirmation" %>
	     		<%= f.password_field :password_confirmation %>
	     	</div>

	     	<%= f.submit "Create my account", class: "btn btn-primary" %>
	    <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% @title=@user.name %>
<% if @user.public_avatar %>
    <% @icon=gravatar_for(@user) %>
<% else %>
    <% @icon='<i class="material-icons">face</i>'.html_safe %>
<% end %>

<% if current_user == @user %>
    <div id="error_explanation" class="card" style="color: red;">
    </div>

    <div class="card">
      <div class="card-content">
        <span class="card-title">Edit User</span><br>
        <%= form_for @user, remote: true do |f| %>
          <div class="input-field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <div class="input-field">
            <%= f.label :interests %>
            <%= f.text_area :interests, class: "materialize-textarea", style: "padding-bottom: 12px;" %>
          </div>
          <div class="switch" style="margin-bottom: 2rem;margin-top: 1rem;"><label>Show default avatar <%= f.check_box :public_avatar %><span class="lever"></span> Use gravatar avatar</label></div>
          <p class="right">Change avatar on <%= link_to "gravatar.com", "http://gravatar.com" %></p>
          <%= f.submit class: "btn-flat waves-effect waves-light" %>
        <% end %>
      </div>
    </div>

	<%= render 'group/form' %>

	<% @user.groups.each do |group| %>
  	<div class="card">
  		<div class="card-content">
  			<span class="card-title"><%= group.name %><div class="chip secondary-content">owner</div></span>
        <% if group.people.any?{|person|person.user_id==current_user.id} %>
          <% person = group.people.select{|person|person.user_id==current_user.id}.first %>
          <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %>
            <br>Sending to: 
            <p style="display: inline;">
              <% giving =  Person.find(person.giving_to) %>
              <% if giving.user_id and User.exists?(giving.user_id) %>
                <%= link_to giving.name, User.find(giving.user_id) %>
              <% else %>
                <%= giving.name %>
              <% end %>
            </p>
          <% end %>
          <% if not person.receiving_from.nil? and Person.exists?(person.receiving_from) %>
            <br>Receiving from: 
            <p style="display: inline;">
              <% receiving =  Person.find(person.receiving_from) %>
              <% if receiving.user_id and User.exists?(receiving.user_id) %>
                <%= link_to receiving.name, User.find(receiving.user_id) %>
              <% else %>
                <%= receiving.name %>
              <% end %>
            </p>
          <% end %>
        <% end %>
		  </div>
		  <div class="card-action">
			  <%= link_to "Open", group_path(group) %>
			  <%= link_to 'Delete', group_path(group),
            	method: :delete,
            	data: { confirm: 'Are you sure?' } %>
  			<%= link_to 'Duplicate', duplicate_path(group), 
            	method: :post,
            	remote: true %>
		  </div>
	  </div>
  <% end %>

  <% Group.all.select{|group| group.people.any?{|person|person.user_id==current_user.id and not @user.groups.include?(group)}}.each do |group| %>
    <% person = group.people.select{|person|person.user_id==current_user.id}.first %>
    <div class="card">
      <div class="card-content">
        <span class="card-title"><%= group.name %></span>
        <% if not person.giving_to.nil? and Person.exists?(person.giving_to) %>
          <br>Sending to: 
          <p style="display: inline;">
            <% giving =  Person.find(person.giving_to) %>
            <% if giving.user_id and User.exists?(giving.user_id) %>
              <%= link_to giving.name, User.find(giving.user_id) %>
            <% else %>
              <%= giving.name %>
            <% end %>
          </p>
        <% end %>
        <% if not person.receiving_from.nil? and Person.exists?(person.receiving_from) and group.public? %>
          <br>Receiving from: 
          <p style="display: inline;">
            <% receiving =  Person.find(person.receiving_from) %>
            <% if receiving.user_id and User.exists?(receiving.user_id) %>
              <%= link_to receiving.name, User.find(receiving.user_id) %>
            <% else %>
              <%= receiving.name %>
            <% end %>
          </p>
        <% end %>
      </div>
      <div class="card-action">
        <%= link_to "Open", group_path(group) %>
      </div>
    </div>
  <% end %>
<% elsif not @user.interests.nil? and @user.interests != "" %>
    <div class="card">
        <div class="card-content">
            <span class="card-title">Interests</span><br>
            <%= @user.interests %>
        </div>
    </div>
<% end %>

app/views/users/update.js.erb
<% if @user.errors.any? %>
  $("#error_explanation").html('<ul class="collection with-header"><li class="collection-header"><h4><%= j pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4></li><% @user.errors.full_messages.each do |msg| %><li class="collection-item"><%= j msg %></li><% end %></ul>');
<% else %>
  $("#error_explanation").html('');

  $(".head h1").html('\n<% if @user.public_avatar %><%= gravatar_for(@user) %><% else %><i class="material-icons">face</i><% end %>\n<%= @user.name %>');

  document.title = "<%= @user.name %>";
<% end %>