config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'welcome/index'

  resources :group, param: :code, only: [:show, :create, :update, :destroy] do
    resources :people, only: [:create, :update, :destroy]
    resources :rules, only: [:create, :update, :destroy] do
      resources :tokens, only: [:create, :update, :destroy]
    end
  end

  resources :users

  root 'welcome#index'

  get     '/group/:code/admin',     to: 'group#show'
  get     '/signup',                to: 'users#new'
  get     '/login',                 to: 'sessions#new'
  post    '/',                      to: 'group#create'
  post    '/search',                to: 'group#search'
  post    '/group/:code/generate',  to: 'group#randomize',  as: 'generate'
  post    '/group/:code/duplicate',  to: 'group#duplicate',  as: 'duplicate'
  post    '/group/:code/clear',     to: 'group#clear',      as: 'clear'
  post    '/signup',                to: 'users#create'
  post    '/login',                 to: 'sessions#create'
  delete  '/logout',                to: 'sessions#destroy'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :store_target_location
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_form.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation" class="card" style="color: red;">
    <ul class="collection with-header">
      <li class="collection-header">
        <h4>
          <%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:
        </h4>
      </li>
      <% @group.errors.full_messages.each do |msg| %>
        <li class="collection-item"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="card">
  <div class="card-content">
    <%= form_for @group, url: '/', method: 'post', class: "col s12" do |f| %>
      <span class="card-title">Create Group</span>
      <div class="input-field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="input-field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <%= f.submit class: "btn-flat waves-effect waves-light" %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<% @title="Name Draw" %>

<% if @notfound %>
  <div class="card" style="color: red;">
    <div class="card-content">
      Group not found
    </div>
  </div>
<% end %>

<div class="card">
  <div class="card-content">
    <%= form_tag search_path, class: "col s12" do %>
      <span class="card-title">Open Group</span>
      <div class="input-field">
        <%= label_tag :code %>
        <%= text_field_tag :code %>
      </div>
      <%= submit_tag "Open Group", class: "btn-flat waves-effect waves-light" %>
    <% end %>
  </div>
</div>

<p>To create a group <%= link_to "register", signup_path %> or <%= link_to "login", login_path %></p>